# Generated by Django 6.0.2 on 2026-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_options_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
