# Generated by Django 6.0.2 on 2026-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
