# Generated by Django 6.0.2 on 2026-02-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('menuitem', '0003_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.branch'),
            preserve_default=False,
        ),
    ]
